In [3]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Define the tweet URL
url = 'https://twitter.com/westerosies/status/1632423392279183360'

# Define empty lists to store comments and replies
comments_list = []
replies_list = []

# Define a function to extract replies
def extract_replies(comment):
    for tweet in sntwitter.TwitterSearchScraper('to:' + comment.url).get_items():
        if tweet.inReplyToTweetId == comment.id:
            replies_list.append(tweet)
            extract_replies(tweet)

            # Scrape comments
for tweet in sntwitter.TwitterSearchScraper('url:' + url).get_items():
    if tweet.inReplyToTweetId is None:
        comments_list.append(tweet)
        extract_replies(tweet)

# Convert comments and replies lists to Pandas DataFrames
comments_df = pd.DataFrame(comments_list)
replies_df = pd.DataFrame(replies_list)

# Save comments and replies to CSV files
comments_df.to_csv('comments.csv', index=False)
replies_df.to_csv('replies.csv', index=False)

In [7]:
comments_df

,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe
0,https://twitter.com/Nocturnalusers/status/1638...,2023-03-23 15:46:29+00:00,I'd still say all seasons except season 8,I'd still say all seasons except season 8,1638930221889118209,"{'username': 'Nocturnalusers', 'id': 134754454...",0,0,0,0,...,None,None,None,None,None,None,None,None,40,None
1,https://twitter.com/xkjulia7/status/1635781164...,2023-03-14 23:13:15+00:00,la cuarta y la sexta sí o sí,la cuarta y la sexta sí o sí,1635781164194512896,"{'username': 'xkjulia7', 'id': 122180542330253...",1,0,0,0,...,None,None,None,None,None,None,None,None,52,None
2,https://twitter.com/qwophi_emma/status/1635314...,2023-03-13 16:18:20+00:00,Season 4 &amp; 6,Season 4 &amp; 6,1635314358657122306,"{'username': 'qwophi_emma', 'id': 920658061194...",0,0,0,0,...,None,None,None,None,None,None,None,None,101,None
3,https://twitter.com/Macientismo/status/1634970...,2023-03-12 17:32:58+00:00,"1,3 e 4 o resto é trash","1,3 e 4 o resto é trash",1634970751160942599,"{'username': 'Macientismo', 'id': 156727478996...",0,0,0,0,...,None,None,None,None,None,None,None,None,22,None
4,https://twitter.com/BTCoroa00/status/163492914...,2023-03-12 14:47:37+00:00,O poster da segunda e da sétima é putaria,O poster da segunda e da sétima é putaria,1634929141538783234,"{'username': 'BTCoroa00', 'id': 16027722365067...",0,0,0,0,...,None,None,None,None,None,None,None,None,35,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,https://twitter.com/0cta_0/status/163242384547...,2023-03-05 16:52:28+00:00,4 ama 6,4 ama 6,1632423845478154241,"{'username': '0cta_0', 'id': 15370003173087641...",0,0,0,0,...,None,None,None,None,None,None,None,None,103,None
684,https://twitter.com/jinlipeh/status/1632423724...,2023-03-05 16:51:59+00:00,4 e 6,4 e 6,1632423724052783105,"{'username': 'jinlipeh', 'id': 2852607917, 'di...",0,0,1,0,...,None,None,None,None,None,None,None,None,129,None
685,https://twitter.com/yulyunieiei/status/1632423...,2023-03-05 16:51:50+00:00,"season4,6","season4,6",1632423686300119041,"{'username': 'yulyunieiei', 'id': 939113378458...",0,0,0,0,...,None,None,None,None,None,None,None,None,85,None
686,https://twitter.com/a_borze/status/16324236410...,2023-03-05 16:51:39+00:00,"La saison 4, sans aucun débat possible.","La saison 4, sans aucun débat possible.",1632423641009856512,"{'username': 'a_borze', 'id': 4441573721, 'dis...",0,0,0,0,...,None,None,None,None,None,None,None,None,59,None
687,https://twitter.com/westerosies/status/1632423...,2023-03-05 16:50:40+00:00,Which Game Of Thrones season is the most re-wa...,Which Game Of Thrones season is the most re-wa...,1632423392279183360,"{'username': 'westerosies', 'id': 148261237572...",657,468,8982,985,...,None,None,None,None,None,None,None,None,940079,None

In [6]:
replies_df.head()

Empty DataFrame
Columns: []
Index: []